/*
 * Copyright (C) 2018 - 2018 Naoghuman's dream
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.github.naoghuman.lib.preferences.internal;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * UnitTests to test the default implementation 
 * {@link com.github.naoghuman.lib.preferences.internal.DefaultPreferencesProperties}.
 *
 * @since   0.6.0
 * @version 0.6.0
 * @author  Naoghuman
 * @see     com.github.naoghuman.lib.preferences.internal.DefaultPreferencesProperties
 */
public class DefaultPreferencesPropertiesTest {
    
    public DefaultPreferencesPropertiesTest() {
    }
    
    @Before
    public void setUp() {
    }
    
    @After
    public void tearDown() {
    }
    
    @Test
    public void writeFilePreferencesWithDefaultCommentary() {
        String pathPlusFile = System.getProperty("user.dir")
                + File.separator
                + "Preferences_"
                + System.nanoTime()
                + ".properties";
        
        File file = new File(pathPlusFile);
        assertFalse(file.exists());
        
        DefaultPreferencesProperties defaultPreferencesProperties = new DefaultPreferencesProperties();
        DefaultPreferencesFileWriter.write(defaultPreferencesProperties, file);
        
        File file2 = new File(pathPlusFile);
        assertTrue(file2.exists());
        
        boolean foundDefaultCommentary = Boolean.FALSE;
        try(final BufferedReader reader = new BufferedReader(new FileReader (file))) {
            String line = "";
             while ((line = reader.readLine()) != null) {
                if (line.contains("This file is automatically generated. Plz don't modified it manually.")) {
                    foundDefaultCommentary = Boolean.TRUE;
                    break;
                }
            }
        } catch (IOException ioe) { }
        
        assertTrue(foundDefaultCommentary);
        
        if (file.exists()) {
            assertTrue(file.delete());
        }
    }
    
    @Test
    public void writeFilePreferencesWithOwnCommentary() {
        String pathPlusFile = System.getProperty("user.dir")
                + File.separator
                + "Preferences_"
                + System.nanoTime()
                + ".properties";
        
        File file = new File(pathPlusFile);
        assertFalse(file.exists());
        
        DefaultPreferencesProperties defaultPreferencesProperties = new DefaultPreferencesProperties();
        DefaultPreferencesFileWriter.write(defaultPreferencesProperties, file, "Own commentary");
        
        File file2 = new File(pathPlusFile);
        assertTrue(file2.exists());
        
        boolean foundDefaultCommentary = Boolean.FALSE;
        try(final BufferedReader reader = new BufferedReader(new FileReader (file))) {
            String line = "";
            while ((line = reader.readLine()) != null) {
                if (line.contains("Own commentary")) {
                    foundDefaultCommentary = Boolean.TRUE;
                    break;
                }
            }
        } catch (IOException ioe) { }
        
        assertTrue(foundDefaultCommentary);
        
        if (file.exists()) {
            assertTrue(file.delete());
        }
    }
    
}
