/**
 * Copyright (C) 2018 Naoghuman
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.github.naoghuman.lib.preferences.internal;

import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

/**
 *
 * @author Naoghuman
 * @since  0.6.0
 */
final class DefaultPreferencesFileWriter implements PreferencesWriter {

    @Override
    public void write(final File file, final PreferencesProperties properties) {
        
        try(final BufferedOutputStream bos = new BufferedOutputStream(new FileOutputStream(file))) {
            properties.store(bos, "This file is automatically generated. Plz don't modified it manuelly."); // NOI18N
        } catch (IOException e) {
            
        }
    }
    
}
